### PR TITLE
GCC-14

### PR DESCRIPTION
**Pull request by benbierens**
In GCC-14, pointer compatibility warnings have been promoted to errors.
This applies a compatible pointer type definition.

### CODE REVIEW

**Review by markspanbroek — APPROVED** [review]
:+1:

**Comment by tersec** [comment]
As a general note, eventually if one can at some point in the future depend on Nim 2.0.8 or newer being available, this workaround will become redundant.

**Comment by arnetheduck** [comment]
what about compilers for which the flag does not exist (`clang`, older gcc etc)? ie has the option to actually fix the pointers been explored?

**Comment by benbierens** [comment]
> what about compilers for which the flag does not exist (`clang`, older gcc etc)? ie has the option to actually fix the pointers been explored?

I did look into that. I was unable to find out what the nim equivalent of the C type should be. It's a `const void* const * const`. Clearly it aligns with nim `ptr pointer`, but I have no idea how to make GCC see that. If you have the answer, I'd be happy to learn a thing or two!

**Comment by arnetheduck** [comment]
Most our libraries have had to go through this process such as https://github.com/status-im/nim-bearssl/pull/62 - just look for gcc 14 in any bumped deps.

**Comment by benbierens** [comment]
OK that was disgustingly simple. Thanks so much, Arne!

**Pull request merged**
